Imports Guna.UI2.WinForms

Module DarkModeManager
    Public Sub ToggleDarkMode(ByVal form As Form, ByVal isDarkMode As Boolean)
        ' Your code to toggle dark mode goes here
        ' Example: Setting form's BackColor
        If isDarkMode Then
            frmForm4.BackColor = Color.FromArgb(64, 64, 64)
            frmForm4.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(64, 64, 64)
            frmForm4.Guna2CustomGradientPanel1.FillColor2 = Color.DimGray
            frmForm4.Guna2CustomGradientPanel1.FillColor3 = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2CustomGradientPanel1.FillColor2 = Color.DimGray
            CreateOrder.Guna2CustomGradientPanel1.FillColor3 = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2Panel1.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2Panel2.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2Panel4.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2Panel5.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Panel2.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2Panel7.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2Panel8.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Guna2Panel9.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.Panel1.BackColor = Color.FromArgb(64, 64, 64)
            CreateOrder.dtpDateToPickUp.FillColor = Color.Silver
            CreateOrder.btnSave.FillColor = Color.Silver
            CreateOrder.btnCompute.FillColor = Color.Silver
            CreateOrder.cmbGarments.FillColor = Color.Silver
            CreateOrder.cmbService.FillColor = Color.Silver
            CreateOrder.cbxSelfService.ForeColor = Color.White
            CreateOrder.cmbfabcon.FillColor = Color.Silver
            CreateOrder.cmbpowder.FillColor = Color.Silver
            CreateOrder.txtTotal.ForeColor = Color.White
            CreateOrder.label.ForeColor = Color.White
            CreateOrder.txtOrderNum.ForeColor = Color.White
            CreateOrder.Label9.ForeColor = Color.White
            CreateOrder.Label10.ForeColor = Color.White
            CreateOrder.Label11.ForeColor = Color.White
            CreateOrder.Label12.ForeColor = Color.White
            CreateOrder.Label14.ForeColor = Color.White
            CreateOrder.Label4.ForeColor = Color.White
            CreateOrder.Label13.ForeColor = Color.White
            CreateOrder.Label6.ForeColor = Color.White
            CreateOrder.Label2.ForeColor = Color.White
            CreateOrder.Label3.ForeColor = Color.White
            CreateOrder.Label7.ForeColor = Color.White
            CreateOrder.Label8.ForeColor = Color.White
            CreateOrder.Label1.ForeColor = Color.White
            CreateOrder.Label15.ForeColor = Color.White

            Home_Page.Panel1.BackColor = Color.FromArgb(64, 64, 64)
            Home_Page.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(64, 64, 64)
            Home_Page.Guna2CustomGradientPanel1.FillColor2 = Color.DimGray
            Home_Page.Guna2CustomGradientPanel1.FillColor3 = Color.FromArgb(64, 64, 64)
            Home_Page.btnAboutus.FillColor = Color.FromArgb(64, 64, 64)
            'Home_Page.btnCreate.FillColor = Color.FromArgb(64, 64, 64)
            Home_Page.btnSettings.FillColor = Color.FromArgb(64, 64, 64)
            Home_Page.btnUpdate.FillColor = Color.FromArgb(64, 64, 64)
            Home_Page.PanelMenu.BackColor = Color.FromArgb(64, 64, 64)
            Home_Page.Guna2Button1.FillColor = Color.FromArgb(64, 64, 64)
            frmForm3.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(64, 64, 64)
            frmForm3.Guna2CustomGradientPanel1.FillColor2 = Color.DimGray
            frmForm3.Guna2CustomGradientPanel1.FillColor3 = Color.FromArgb(64, 64, 64)
            frmForm3.Orders.BackgroundColor = Color.Silver
            'frmForm5.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(64, 64, 64)
            'frmForm5.Guna2CustomGradientPanel1.FillColor2 = Color.DimGray
            'frmForm5.Guna2CustomGradientPanel1.FillColor3 = Color.FromArgb(64, 64, 64)
            frmForm5.Label3.ForeColor = Color.White
            frmForm5.Label4.ForeColor = Color.White
            'frmForm5.Label5.ForeColor = Color.White
            'frmForm5.Label6.ForeColor = Color.White
            'frmForm5.Label7.ForeColor = Color.White
            frmForm5.Panel2.BackColor = Color.FromArgb(64, 64, 64)
            frmForm5.Panel3.BackColor = Color.FromArgb(64, 64, 64)
            frmForm5.Panel1.BackColor = Color.FromArgb(64, 64, 64)
            frmForm5.Panel2.BackColor = Color.FromArgb(64, 64, 64)
            frmForm5.Panel3.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(64, 64, 64)
            EditForm.Guna2CustomGradientPanel1.FillColor2 = Color.DimGray
            EditForm.Guna2CustomGradientPanel1.FillColor3 = Color.FromArgb(64, 64, 64)
            EditForm.Guna2Panel1.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.Guna2Panel2.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.Guna2Panel4.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.Guna2Panel5.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.Panel2.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.Guna2Panel7.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.Guna2Panel8.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.Guna2Panel9.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.BackColor = Color.FromArgb(64, 64, 64)
            EditForm.dtpDateToPickUp.FillColor = Color.Silver
            EditForm.btnSave.FillColor = Color.Silver
            EditForm.btnCompute.FillColor = Color.Silver
            EditForm.cmbGarments.FillColor = Color.Silver
            EditForm.cmbService.FillColor = Color.Silver
            EditForm.cbxSelfService.ForeColor = Color.White
            EditForm.cmbfabcon.FillColor = Color.Silver
            EditForm.cmbpowder.FillColor = Color.Silver
            EditForm.txtTotal.ForeColor = Color.White
            EditForm.label.ForeColor = Color.White
            EditForm.txtOrderNum.ForeColor = Color.White
            EditForm.Label9.ForeColor = Color.White
            EditForm.Label10.ForeColor = Color.White
            EditForm.Label11.ForeColor = Color.White
            EditForm.Label12.ForeColor = Color.White
            EditForm.Label14.ForeColor = Color.White
            EditForm.Label4.ForeColor = Color.White
            EditForm.Label13.ForeColor = Color.White
            EditForm.Label6.ForeColor = Color.White
            EditForm.Label2.ForeColor = Color.White
            EditForm.Label3.ForeColor = Color.White
            EditForm.Label7.ForeColor = Color.White
            EditForm.Label8.ForeColor = Color.White
            EditForm.Label1.ForeColor = Color.White
            'EditForm.btnDelete.FillColor = Color.Silver
            EditForm.Label15.ForeColor = Color.Black
            Login_Form.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(64, 64, 64)
            Login_Form.Guna2CustomGradientPanel1.FillColor2 = Color.DimGray
            Login_Form.Guna2CustomGradientPanel1.FillColor3 = Color.FromArgb(64, 64, 64)
            Login_Form.Guna2Button1.FillColor = Color.FromArgb(64, 64, 64)
            ChangePass.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(64, 64, 64)
            ChangePass.Guna2CustomGradientPanel1.FillColor2 = Color.DimGray
            ChangePass.Guna2CustomGradientPanel1.FillColor3 = Color.FromArgb(64, 64, 64)
            ChangePass.btnChangePass.FillColor = Color.FromArgb(64, 64, 64)
        Else
            frmForm4.BackColor = Color.White
            frmForm4.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(56, 122, 223)
            frmForm4.Guna2CustomGradientPanel1.FillColor2 = Color.White
            frmForm4.Guna2CustomGradientPanel1.FillColor3 = Color.DodgerBlue
            CreateOrder.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(56, 122, 223)
            CreateOrder.Guna2CustomGradientPanel1.FillColor2 = Color.White
            CreateOrder.Guna2CustomGradientPanel1.FillColor3 = Color.DodgerBlue
            CreateOrder.Guna2Panel1.BackColor = Color.White
            CreateOrder.Guna2Panel2.BackColor = Color.White
            CreateOrder.Guna2Panel4.BackColor = Color.White
            CreateOrder.Guna2Panel5.BackColor = Color.White
            CreateOrder.Panel2.BackColor = Color.White
            CreateOrder.Guna2Panel7.BackColor = Color.White
            CreateOrder.Guna2Panel8.BackColor = Color.White
            CreateOrder.Guna2Panel9.BackColor = Color.White
            CreateOrder.Panel1.BackColor = Color.White
            CreateOrder.dtpDateToPickUp.FillColor = Color.FromArgb(56, 122, 223)
            CreateOrder.btnSave.FillColor = Color.FromArgb(56, 122, 223)
            CreateOrder.btnCompute.FillColor = Color.FromArgb(56, 122, 223)
            CreateOrder.cmbGarments.FillColor = Color.White
            CreateOrder.cmbService.FillColor = Color.White
            CreateOrder.cbxSelfService.ForeColor = Color.Black
            CreateOrder.cmbfabcon.FillColor = Color.White
            CreateOrder.cmbpowder.FillColor = Color.White
            CreateOrder.txtTotal.ForeColor = Color.Black
            CreateOrder.label.ForeColor = Color.Black
            CreateOrder.txtOrderNum.ForeColor = Color.Black
            CreateOrder.Label9.ForeColor = Color.Black
            CreateOrder.Label10.ForeColor = Color.Black
            CreateOrder.Label11.ForeColor = Color.Black
            CreateOrder.Label12.ForeColor = Color.Black
            CreateOrder.Label14.ForeColor = Color.Black
            CreateOrder.Label4.ForeColor = Color.Black
            CreateOrder.Label13.ForeColor = Color.Black
            CreateOrder.Label6.ForeColor = Color.Black
            CreateOrder.Label2.ForeColor = Color.Black
            CreateOrder.Label3.ForeColor = Color.Black
            CreateOrder.Label7.ForeColor = Color.Black
            CreateOrder.Label8.ForeColor = Color.Black
            CreateOrder.Label1.ForeColor = Color.Black
            CreateOrder.Label15.ForeColor = Color.Black
            Home_Page.Panel1.BackColor = Color.FromArgb(56, 122, 223)
            Home_Page.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(56, 122, 223)
            Home_Page.Guna2CustomGradientPanel1.FillColor2 = Color.White
            Home_Page.Guna2CustomGradientPanel1.FillColor3 = Color.DodgerBlue
            Home_Page.btnAboutus.FillColor = Color.FromArgb(56, 122, 223)
            'Home_Page.btnCreate.FillColor = Color.FromArgb(56, 122, 223)
            Home_Page.btnSettings.FillColor = Color.FromArgb(56, 122, 223)
            Home_Page.btnUpdate.FillColor = Color.FromArgb(56, 122, 223)
            Home_Page.PanelMenu.BackColor = Color.FromArgb(56, 122, 223)
            Home_Page.Guna2Button1.FillColor = Color.FromArgb(56, 122, 223)
            frmForm3.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(56, 122, 223)
            frmForm3.Guna2CustomGradientPanel1.FillColor2 = Color.White
            frmForm3.Guna2CustomGradientPanel1.FillColor3 = Color.DodgerBlue
            frmForm3.Label1.ForeColor = Color.Black
            frmForm3.Orders.BackgroundColor = Color.White
            'frmForm5.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(56, 122, 223)
            'frmForm5.Guna2CustomGradientPanel1.FillColor2 = Color.White
            'frmForm5.Guna2CustomGradientPanel1.FillColor3 = Color.DodgerBlue
            frmForm5.Label3.ForeColor = Color.Black
            frmForm5.Label4.ForeColor = Color.Black
            'frmForm5.Label5.ForeColor = Color.Blue
            'frmForm5.Label6.ForeColor = Color.Blue
            'frmForm5.Label7.ForeColor = Color.Blue
            frmForm5.Panel2.BackColor = Color.White
            frmForm5.Panel3.BackColor = Color.White
            frmForm5.Panel1.BackColor = Color.White
            frmForm5.Panel2.BackColor = Color.White
            frmForm5.Panel3.BackColor = Color.White
            EditForm.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(56, 122, 223)
            EditForm.Guna2CustomGradientPanel1.FillColor2 = Color.White
            EditForm.Guna2CustomGradientPanel1.FillColor3 = Color.DodgerBlue
            EditForm.Guna2Panel1.BackColor = Color.White
            EditForm.Guna2Panel2.BackColor = Color.White
            EditForm.Guna2Panel4.BackColor = Color.White
            EditForm.Guna2Panel5.BackColor = Color.White
            EditForm.Panel2.BackColor = Color.White
            EditForm.Guna2Panel7.BackColor = Color.White
            EditForm.Guna2Panel8.BackColor = Color.White
            EditForm.Guna2Panel9.BackColor = Color.White
            EditForm.BackColor = Color.White
            EditForm.dtpDateToPickUp.FillColor = Color.FromArgb(56, 122, 223)
            EditForm.btnSave.FillColor = Color.FromArgb(56, 122, 223)
            EditForm.btnCompute.FillColor = Color.FromArgb(56, 122, 223)
            EditForm.cmbGarments.FillColor = Color.White
            EditForm.cmbService.FillColor = Color.White
            EditForm.cbxSelfService.ForeColor = Color.Black
            EditForm.cmbfabcon.FillColor = Color.White
            EditForm.cmbpowder.FillColor = Color.White
            EditForm.txtTotal.ForeColor = Color.Black
            EditForm.label.ForeColor = Color.Black
            EditForm.txtOrderNum.ForeColor = Color.Black
            EditForm.Label9.ForeColor = Color.Black
            EditForm.Label10.ForeColor = Color.Black
            EditForm.Label11.ForeColor = Color.Black
            EditForm.Label12.ForeColor = Color.Black
            EditForm.Label14.ForeColor = Color.Black
            EditForm.Label4.ForeColor = Color.Black
            EditForm.Label13.ForeColor = Color.Black
            EditForm.Label6.ForeColor = Color.Black
            EditForm.Label2.ForeColor = Color.Black
            EditForm.Label3.ForeColor = Color.Black
            EditForm.Label7.ForeColor = Color.Black
            EditForm.Label8.ForeColor = Color.Black
            EditForm.Label1.ForeColor = Color.Black
            EditForm.Label15.ForeColor = Color.Black
            'EditForm.btnDelete.FillColor = Color.FromArgb(56, 122, 223)
            Login_Form.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(56, 122, 223)
            Login_Form.Guna2CustomGradientPanel1.FillColor2 = Color.White
            Login_Form.Guna2CustomGradientPanel1.FillColor3 = Color.DodgerBlue
            Login_Form.Guna2Button1.FillColor = SystemColors.HotTrack
            ChangePass.Guna2CustomGradientPanel1.FillColor = Color.FromArgb(56, 122, 223)
            ChangePass.Guna2CustomGradientPanel1.FillColor2 = Color.White
            ChangePass.Guna2CustomGradientPanel1.FillColor3 = Color.DodgerBlue
            ChangePass.btnChangePass.FillColor = Color.FromArgb(0, 0, 192)
        End If
    End Sub
End Module
